import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import HomeView from "../views/home/index"
import { getOngs } from '@/lib'
import { GetStaticProps } from 'next'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Be the Hero</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeView />
    </>
  )
}
export const getStaticProps: GetStaticProps = async () =>{
  const ongs = await getOngs()
  return{
    props:{
      ongs
    }
  }
}